[win_domain]
172.16.1.2
172.16.1.20
172.16.1.13

[win_local]
172.16.1.11
172.16.1.12

[win_domain:vars]
ansible_user=ccadmin@internal.georgieandchris.com
ansible_password=P@ssw0rd
ansible_connection=winrm
ansible_winrm_scheme=https
ansible_winrm_transport=ntlm
ansible_connection_port=5986
ansible_winrm_server_cert_validation=ignore

[win_local:vars]
ansible_user=administrator
ansible_password=P@ssw0rd
ansible_connection=winrm
ansible_winrm_scheme=https
ansible_winrm_transport=ntlm
ansible_connection_port=5986
ansible_winrm_server_cert_validation=ignore