- name: Join Rocky Linux server to AD domain
  hosts: all
  become: yes
  vars:
    domain_name: "internal.georgieandchris.com"
    domain_admin_user: "ccadmin"
    domain_admin_password: "P@ssw0rd"
    #ad_ou: "OU=Georgie and Chris Computers,DC=internal,DC=georgieandchris,DC=com" # Optional, specify the OU if needed

  tasks:
    - name: Install required packages
      ansible.builtin.yum:
        name:
          - realmd
          - sssd
          - krb5-workstation
          - samba-common-tools
          - oddjob
          - oddjob-mkhomedir
          - adcli
        state: present

    - name: Ensure oddjobd service is enabled and started
      ansible.builtin.systemd:
        name: oddjobd
        enabled: yes
        state: started

    - name: Discover the domain
      ansible.builtin.command:
        cmd: realm discover {{ domain_name }}
      register: realm_discover
      ignore_errors: yes

    - name: Join the server to the AD domain
      ansible.builtin.command:
        cmd: echo {{ domain_admin_password }} | realm join --user={{ domain_admin_user }} {{ domain_name }}
      when: realm_discover.rc == 0

    - name: Verify if the keytab file exists
      ansible.builtin.stat:
        path: /etc/krb5.keytab
      register: krb5_keytab

    - name: Create keytab file if not present using net ads
      ansible.builtin.command:
        cmd: net ads keytab create -U {{ domain_admin_user }}%{{ domain_admin_password }}
      when: not krb5_keytab.stat.exists

    - name: Create /etc/sssd directory if it does not exist
      ansible.builtin.file:
        path: /etc/sssd
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create /etc/sssd/sssd.conf if it does not exist
      ansible.builtin.copy:
        dest: /etc/sssd/sssd.conf
        content: |
          [sssd]
          domains = {{ domain_name }}
          config_file_version = 2
          services = nss, pam

          [domain/{{ domain_name }}]
          id_provider = ad
          auth_provider = ad
          access_provider = ad
          chpass_provider = ad
          cache_credentials = True
          ad_domain = {{ domain_name }}
          krb5_realm = {{ domain_name | upper }}
          realmd_tags = manages-system joined-with-samba
          default_shell = /bin/bash
          fallback_homedir = /home/%u@%d
          access_provider = simple
        owner: root
        group: root
        mode: '0600'
      when: realm_discover.rc == 0

    - name: Ensure SSSD service is enabled and started
      ansible.builtin.systemd:
        name: sssd
        enabled: yes
        state: started

    - name: Configure SSSD to use AD
      ansible.builtin.lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^domains'
        line: 'domains = {{ domain_name }}'
        state: present

    - name: Restart SSSD service
      ansible.builtin.systemd:
        name: sssd
        state: restarted
