---
- name: "Add Rocky Linux server to Active Directory domain"
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      ansible.builtin.yum:
        name:
          - realmd
          - sssd
          - krb5-workstation
          - samba-common-tools
          - oddjob
          - oddjob-mkhomedir
          - adcli
        state: present

    - name: Join the Active Directory domain
      command: "realm join --user=ccadmin@internal.georgieandchris.com internal.georgieandchris.com --install=/ --verbose"
      become_user: root

    - name: Restart SSSD service
      service:
        name: sssd
        state: restarted