---
- name: Update NXLog Server Config
  hosts: win_domain
  gather_facts: yes

  tasks:
  - name: Check NXLog is installed
    ansible.windows.win_service_info:
      name: NXlog
    register: service_exists
  
  - name: Copy new NXlog config
    ansible.windows.win_get_url:
      url: http://172.16.1.11:8080/homelab/nxlog/-/raw/main/Server/nxlog.conf
      dest: C:\Program Files\nxlog\conf\nxlog.conf
      force: yes
    when: service_exists
    notify: Restart NXLog service

  - name: Copy new NXlog windows_env config
    ansible.windows.win_get_url:
      url: http://172.16.1.11:8080/homelab/nxlog/-/raw/main/Server/windows_env.cmd
      dest: C:\Program Files\nxlog\conf\windows_env.cmd
      force: yes
    when: service_exists
    notify: Restart NXLog service

  handlers:
  - name: Restart NXLog service
    ansible.windows.win_service:
      name: NXlog
      state: restarted